main.datasource.url=jdbc:hsqldb:file:.jmix/hsqldb/vzvod
server.address=0.0.0.0
main.datasource.username=sa
main.datasource.password=
jmix.data.dbmsType=hsqldb

ui.login.defaultUsername=admin
ui.login.defaultPassword=admin