main.datasource.url=jdbc:hsqldb:file:.jmix/hsqldb/vzvod
server.address=0.0.0.0
main.datasource.username=sa
main.datasource.password=
jmix.data.dbmsType=hsqldb

ui.login.defaultUsername=admin
ui.login.defaultPassword=admin

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ToDo Сделать тесты с Redis