spring.profiles.active=prod

main.liquibase.change-log=com/company/vzvod/liquibase/changelog.xml

jmix.ui.login-view-id=LoginView
jmix.ui.main-view-id=MainView
jmix.ui.menu-config=com/company/vzvod/menu.xml
jmix.ui.composite-menu=true
jmix.ui.menu.position=drawer


jmix.core.available-locales=en,ru

vaadin.launch-browser=false

logging.level.org.atmosphere=warn
logging.level.eclipselink.logging.sql=info
logging.level.io.jmix.core.datastore=info
logging.level.io.jmix.core.AccessLogger=debug
logging.level.io.jmix=info
logging.level.org.springframework.security=info

spring.web.locale=ru_RU
spring.web.locale-resolver=fixed
jmix.localeResolver.defaultLocale=ru_RU
