main.datasource.url=jdbc:hsqldb:file:.jmix/hsqldb/vzvod
server.address=0.0.0.0
main.datasource.username=sa
main.datasource.password=
jmix.data.dbmsType=hsqldb

jmix.ui.login-view-id=LoginView
jmix.ui.main-view-id=MainView
jmix.ui.menu-config=com/company/vzvod/menu.xml
jmix.ui.composite-menu=true
jmix.ui.menu.position=drawer

ui.login.defaultUsername=admin
ui.login.defaultPassword=admin

spring.cache.type=simple