main.datasource.url=jdbc:postgresql://localhost:5432/vzvod_db
main.datasource.username=vzvodadmin
main.datasource.password=GlxgljjV_8
ui.login.defaultUsername=tarasov
ui.login.defaultPassword=Glxgljj_8


spring.cache.type=simple