spring.profiles.active=prod

main.liquibase.change-log=com/company/vzvod/liquibase/changelog.xml

jmix.ui.login-view-id=LoginView
jmix.ui.main-view-id=MainView
jmix.ui.menu-config=com/company/vzvod/menu.xml
jmix.ui.composite-menu=true
jmix.ui.menu.position=drawer


jmix.core.available-locales=en,ru

vaadin.launch-browser=false

logging.level.org.atmosphere=warn
logging.level.eclipselink.logging.sql=info
logging.level.io.jmix.core.datastore=info
logging.level.io.jmix.core.AccessLogger=debug
logging.level.io.jmix=info
logging.level.org.springframework.security=info

spring.web.locale=ru_RU
spring.web.locale-resolver=fixed
jmix.localeResolver.defaultLocale=ru_RU

main.datasource.studio.liquibase.excludePrefixes = qrtz_
spring.quartz.job-store-type = jdbc
spring.quartz.jdbc.initialize-schema = always
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=event-parser-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=practice.dto

server.port=8080